services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8001:8001"
    networks:
      - internal
    restart: unless-stopped

  docparser:
    build:
      context: ..
      dockerfile: docker/Dockerfile.docparser
    networks:
      - internal

  risk-calculator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.risk-calculator
    networks:
      - internal

networks:
  internal:
    driver: bridge