services:

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env
    ports:
      - "8001:8001"
    networks:
      - internal
    restart: unless-stopped

  docparser:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env
    command: ["python", "-m", "app.services.doc_parser.doc_parser"]
    networks:
      - internal

  risk-calculator:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    env_file:
      - ../.env
    command: ["python", "-m", "app.services.risk_calculator.risk_calculator"]
    networks:
      - internal

networks:
  internal:
    driver: bridge
